"""`shamal plan` end-to-end with a stubbed LLM (spec: scenario-generation)."""

from pathlib import Path

import pytest
from typer.testing import CliRunner

import shamal.cli
from shamal.cli import app
from shamal.exitcodes import ExitCode
from shamal.scenario import Journey, ScenarioSpec, Stage, Step

runner = CliRunner()

FIXTURES = Path(__file__).parent / "fixtures"

STUB_SPEC = ScenarioSpec(
    name="petstore-load",
    base_url="https://api.petstore.example",
    journeys=[
        Journey(
            name="list and create pets",
            steps=[
                Step(method="GET", path="/pets?status=available"),
                Step(method="POST", path="/pets", body={"name": "smoky"}, expect_status=201),
            ],
        )
    ],
    stages=[Stage(duration="30s", target=5), Stage(duration="1m", target=25)],
)


@pytest.fixture
def stubbed_generation(monkeypatch: pytest.MonkeyPatch) -> None:
    """Bypass the LLM: generation returns a fixed spec; everything else is real."""
    monkeypatch.setattr(shamal.cli, "generate_scenario", lambda source, client: STUB_SPEC)
    monkeypatch.setenv("SHAMAL_MODEL", "claude-sonnet-5")


def plan(tmp_path: Path, *extra: str) -> object:
    out = tmp_path / "scenario.js"
    return runner.invoke(
        app, ["plan", str(FIXTURES / "petstore.yaml"), "--out", str(out), *extra]
    )


class TestPlanCommand:
    def test_writes_scenario_with_provenance(
        self, tmp_path: Path, stubbed_generation: None
    ) -> None:
        result = plan(tmp_path)
        assert result.exit_code == ExitCode.OK, result.output  # type: ignore[attr-defined]
        content = (tmp_path / "scenario.js").read_text(encoding="utf-8")
        assert content.startswith("// Generated by Shamal")
        assert "petstore.yaml" in content.splitlines()[0] or "petstore.yaml" in content

    def test_review_prints_summary(self, tmp_path: Path, stubbed_generation: None) -> None:
        result = plan(tmp_path, "--review")
        output = result.output  # type: ignore[attr-defined]
        assert "list and create pets" in output
        assert "GET /pets?status=available" in output
        assert "30s" in output and "1m" in output
        assert "p(95)<500" in output

    def test_existing_file_protected_without_force(
        self, tmp_path: Path, stubbed_generation: None
    ) -> None:
        precious = tmp_path / "scenario.js"
        precious.write_text("// hand-tuned, do not clobber", encoding="utf-8")
        result = plan(tmp_path)
        assert result.exit_code == ExitCode.CONFIG_ERROR  # type: ignore[attr-defined]
        assert precious.read_text(encoding="utf-8") == "// hand-tuned, do not clobber"

    def test_force_overwrites(self, tmp_path: Path, stubbed_generation: None) -> None:
        (tmp_path / "scenario.js").write_text("// old", encoding="utf-8")
        result = plan(tmp_path, "--force")
        assert result.exit_code == ExitCode.OK  # type: ignore[attr-defined]
        assert "// old" not in (tmp_path / "scenario.js").read_text(encoding="utf-8")

    def test_unsupported_source_exits_config_error(
        self, tmp_path: Path, stubbed_generation: None
    ) -> None:
        bad = tmp_path / "notes.txt"
        bad.write_text("prose", encoding="utf-8")
        result = runner.invoke(app, ["plan", str(bad)])
        assert result.exit_code == ExitCode.CONFIG_ERROR  # type: ignore[attr-defined]
