"""Constrained k6 template rendering (spec: scenario-generation).

Every rendered scenario must be syntactically valid JavaScript that plain k6
can execute; validity is checked with `node --check`.
"""

import shutil
import subprocess
from pathlib import Path

import pytest

from shamal.scenario import Journey, ScenarioSpec, Stage, Step, render_scenario

node = shutil.which("node")


def spec_fixture(**overrides: object) -> ScenarioSpec:
    base = {
        "name": "checkout-flow",
        "base_url": "https://shop.example",
        "journeys": [
            Journey(
                name="browse and buy",
                weight=3,
                think_time_s=1.5,
                steps=[
                    Step(method="GET", path="/api/products?category=sale"),
                    Step(
                        method="POST",
                        path="/api/cart",
                        body={"productId": 42, "qty": 1},
                        expect_status=201,
                    ),
                ],
            ),
            Journey(
                name="health check",
                weight=1,
                steps=[Step(method="GET", path="/health")],
            ),
        ],
        "stages": [
            Stage(duration="30s", target=5),
            Stage(duration="2m", target=50),
            Stage(duration="1m", target=0),
        ],
        "thresholds": {
            "http_req_duration": ["p(95)<500"],
            "http_req_failed": ["rate<0.01"],
        },
    }
    base.update(overrides)
    return ScenarioSpec(**base)  # type: ignore[arg-type]


def render_fixture() -> str:
    return render_scenario(spec_fixture(), source_name="petstore.yaml")


class TestRenderedOutput:
    def test_provenance_header_first(self) -> None:
        js = render_fixture()
        head = "\n".join(js.splitlines()[:6])
        assert head.startswith("// Generated by Shamal")
        assert "petstore.yaml" in head
        assert "review" in head.lower() and "edit" in head.lower()

    def test_no_shamal_runtime_imports(self) -> None:
        js = render_fixture()
        assert "shamal" not in js.replace("// Generated by Shamal", "")
        assert "import http from 'k6/http'" in js

    def test_stages_and_thresholds_present(self) -> None:
        js = render_fixture()
        assert '"p(95)<500"' in js
        assert '"rate<0.01"' in js
        assert 'duration: "2m"' in js
        assert "target: 50" in js

    def test_base_url_env_overridable(self) -> None:
        js = render_fixture()
        assert "__ENV.BASE_URL" in js
        assert "https://shop.example" in js

    def test_journeys_rendered_with_weights(self) -> None:
        js = render_fixture()
        assert "browse and buy" in js
        assert "health check" in js
        assert "check(" in js

    @pytest.mark.skipif(node is None, reason="node not installed")
    def test_rendered_js_is_valid(self, tmp_path: Path) -> None:
        out = tmp_path / "scenario.js"
        out.write_text(render_fixture(), encoding="utf-8")
        result = subprocess.run(
            [str(node), "--check", "--input-type=module"],
            input=out.read_text(encoding="utf-8"),
            capture_output=True,
            text=True,
        )
        assert result.returncode == 0, result.stderr

    @pytest.mark.skipif(node is None, reason="node not installed")
    def test_hostile_strings_stay_valid_js(self, tmp_path: Path) -> None:
        """Names and paths with quotes/backslashes must not break the template."""
        spec = spec_fixture(
            journeys=[
                Journey(
                    name="o'brien \"journey\" \\ test",
                    steps=[Step(method="GET", path="/search?q=isn't+it%22")],
                )
            ]
        )
        js = render_scenario(spec, source_name='we"ird.yaml')
        result = subprocess.run(
            [str(node), "--check", "--input-type=module"],
            input=js,
            capture_output=True,
            text=True,
        )
        assert result.returncode == 0, result.stderr


class TestSpecValidation:
    def test_at_least_one_journey_required(self) -> None:
        with pytest.raises(ValueError):
            spec_fixture(journeys=[])

    def test_at_least_one_stage_required(self) -> None:
        with pytest.raises(ValueError):
            spec_fixture(stages=[])

    def test_default_thresholds_applied(self) -> None:
        spec = ScenarioSpec(
            name="minimal",
            base_url="http://localhost:8080",
            journeys=[Journey(name="j", steps=[Step(method="GET", path="/")])],
            stages=[Stage(duration="30s", target=5)],
        )
        assert "http_req_duration" in spec.thresholds
        assert "http_req_failed" in spec.thresholds
