"""End-to-end walkthrough: plan -> run -> investigate -> report.

Only the LLM transport is stubbed (a scripted client); scenario rendering,
the fake-k6 engine, the real agent loop, and report generation all run for
real. This is the closest thing to a user session that runs in CI.
"""

import json
from pathlib import Path

import pytest
from typer.testing import CliRunner

import shamal.llm
from shamal.cli import app
from shamal.exitcodes import ExitCode
from shamal.llm import LLMResponse, TokenUsage
from tests.conftest import FakeK6Factory
from tests.test_agent import FINDING_PAYLOAD, ScriptedClient, submit_response, tool_response

runner = CliRunner()

SPEC_JSON = json.dumps(
    {
        "name": "petstore-load",
        "base_url": "https://api.petstore.example",
        "journeys": [
            {
                "name": "browse pets",
                "weight": 1,
                "think_time_s": 0.5,
                "steps": [
                    {
                        "method": "GET",
                        "path": "/pets?status=available",
                        "headers": {},
                        "body": None,
                        "expect_status": 200,
                    }
                ],
            }
        ],
        "stages": [
            {"duration": "10s", "target": 5},
            {"duration": "30s", "target": 25},
            {"duration": "10s", "target": 0},
        ],
        "thresholds": {
            "http_req_duration": ["p(95)<500"],
            "http_req_failed": ["rate<0.01"],
        },
    }
)


def test_full_walkthrough(
    tmp_path: Path,
    fake_k6: FakeK6Factory,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    fixtures = Path(__file__).parent / "fixtures"
    scripted = ScriptedClient(
        [
            # plan: one completion returning the scenario spec JSON
            LLMResponse(content=SPEC_JSON, usage=TokenUsage()),
            # investigate: consult the knee detector, then conclude
            tool_response("detect_saturation_point", {}),
            submit_response(FINDING_PAYLOAD),
        ]
    )
    monkeypatch.setattr(shamal.llm, "LLMClient", lambda settings: scripted)
    monkeypatch.setenv("SHAMAL_MODEL", "claude-sonnet-5")
    monkeypatch.setenv("SHAMAL_K6_PATH", str(fake_k6()))
    monkeypatch.chdir(tmp_path)

    scenario = tmp_path / "petstore.k6.js"
    results = tmp_path / "results.json"

    plan = runner.invoke(
        app,
        ["plan", str(fixtures / "petstore.yaml"), "--out", str(scenario), "--review"],
    )
    assert plan.exit_code == ExitCode.OK, plan.output
    assert scenario.read_text(encoding="utf-8").startswith("// Generated by Shamal")
    assert "browse pets" in plan.output

    run = runner.invoke(app, ["run", str(scenario), "--results", str(results)])
    assert run.exit_code == ExitCode.OK, run.output
    assert results.is_file()

    investigate = runner.invoke(app, ["investigate", "--results", str(results)])
    assert investigate.exit_code == ExitCode.OK, investigate.output
    assert "DB connection pool exhausted" in investigate.output
    finding_file = tmp_path / "results-finding.json"
    assert finding_file.is_file()

    report = runner.invoke(app, ["report", "--results", str(results)])
    assert report.exit_code == ExitCode.OK, report.output
    report_md = (tmp_path / "results-report.md").read_text(encoding="utf-8")
    assert "PASSED" in report_md.splitlines()[0]
    assert "DB connection pool exhausted" in report_md
    html = (tmp_path / "results-report.html").read_text(encoding="utf-8")
    assert "<svg" in html
