"""ScenarioSpec: the contract between LLM generation and k6 rendering.

The renderer emits plain k6 JavaScript from a fixed skeleton; only data
(names, paths, bodies, stages, thresholds) varies, and every dynamic string
is JSON-escaped. The LLM never writes raw code into the output - that is
what makes generation bounded and the result guaranteed to parse.
"""

from __future__ import annotations

import json
from typing import Any

from pydantic import BaseModel, Field

import shamal

DEFAULT_THRESHOLDS: dict[str, list[str]] = {
    "http_req_duration": ["p(95)<500"],
    "http_req_failed": ["rate<0.01"],
}

_K6_METHOD_FUNCS = {"GET": "get", "POST": "post", "PUT": "put", "PATCH": "patch", "DELETE": "del"}


class Step(BaseModel):
    method: str
    path: str
    name: str | None = None
    headers: dict[str, str] = {}
    body: dict[str, Any] | None = None
    expect_status: int = 200


class Journey(BaseModel):
    name: str
    weight: int = Field(default=1, ge=1)
    think_time_s: float = Field(default=1.0, ge=0)
    steps: list[Step] = Field(min_length=1)


class Stage(BaseModel):
    duration: str
    target: int = Field(ge=0)


class ScenarioSpec(BaseModel):
    name: str
    base_url: str
    journeys: list[Journey] = Field(min_length=1)
    stages: list[Stage] = Field(min_length=1)
    thresholds: dict[str, list[str]] = Field(default_factory=lambda: dict(DEFAULT_THRESHOLDS))


def _js(value: Any) -> str:
    """JSON-escape a value into a safe JavaScript literal."""
    return json.dumps(value, ensure_ascii=False)


def render_scenario(spec: ScenarioSpec, source_name: str) -> str:
    """Render a ScenarioSpec into a standalone k6 script."""
    lines: list[str] = []
    add = lines.append

    add(f"// Generated by Shamal v{shamal.__version__} from {source_name}")
    add("// This is a plain k6 script: review and edit it freely - it runs")
    add("// on its own, with no extra runtime or generator required.")
    add("")
    add("import http from 'k6/http';")
    add("import { check, group, sleep } from 'k6';")
    add("")
    add(f"const BASE_URL = __ENV.BASE_URL || {_js(spec.base_url)};")
    add("")
    add("export const options = {")
    add("  stages: [")
    for stage in spec.stages:
        add(f"    {{ duration: {_js(stage.duration)}, target: {stage.target} }},")
    add("  ],")
    add("  thresholds: {")
    for metric, exprs in spec.thresholds.items():
        add(f"    {_js(metric)}: [{', '.join(_js(e) for e in exprs)}],")
    add("  },")
    add("};")
    add("")

    for index, journey in enumerate(spec.journeys):
        add(f"function journey{index}() {{")
        add(f"  group({_js(journey.name)}, () => {{")
        for step in journey.steps:
            add(_render_step(step))
            if journey.think_time_s > 0:
                add(f"    sleep({journey.think_time_s});")
        add("  });")
        add("}")
        add("")

    add("const JOURNEYS = [")
    for index, journey in enumerate(spec.journeys):
        add(f"  {{ run: journey{index}, weight: {journey.weight} }},")
    add("];")
    add("const TOTAL_WEIGHT = JOURNEYS.reduce((sum, j) => sum + j.weight, 0);")
    add("")
    add("export default function () {")
    add("  let pick = Math.random() * TOTAL_WEIGHT;")
    add("  for (const journey of JOURNEYS) {")
    add("    pick -= journey.weight;")
    add("    if (pick <= 0) { journey.run(); return; }")
    add("  }")
    add("  JOURNEYS[0].run();")
    add("}")
    add("")
    return "\n".join(lines)


def _render_step(step: Step) -> str:
    method = step.method.upper()
    label = step.name or f"{method} {step.path}"
    url = f"BASE_URL + {_js(step.path)}"
    headers = dict(step.headers)
    parts: list[str] = []

    if step.body is not None:
        headers.setdefault("Content-Type", "application/json")
        payload = f"JSON.stringify({_js(step.body)})"
        func = _K6_METHOD_FUNCS.get(method)
        call = (
            f"http.{func}({url}, {payload}, {{ headers: {_js(headers)} }})"
            if func and method != "GET"
            else f"http.request({_js(method)}, {url}, {payload}, {{ headers: {_js(headers)} }})"
        )
    else:
        params = f", {{ headers: {_js(headers)} }}" if headers else ""
        func = _K6_METHOD_FUNCS.get(method)
        call = (
            f"http.{func}({url}{params})"
            if func
            else f"http.request({_js(method)}, {url}, null{params})"
        )

    parts.append(f"    {{ const res = {call};")
    parts.append(
        f"      check(res, {{ {_js(f'{label}: status is {step.expect_status}')}: "
        f"(r) => r.status === {step.expect_status} }}); }}"
    )
    return "\n".join(parts)


def summarize_spec(spec: ScenarioSpec) -> str:
    """Human-readable summary for `shamal plan --review`."""
    lines = [
        f"Scenario: {spec.name}",
        f"Base URL: {spec.base_url} (override with BASE_URL env var)",
        "Journeys:",
    ]
    for journey in spec.journeys:
        lines.append(
            f"  - {journey.name} (weight {journey.weight}, think time {journey.think_time_s}s)"
        )
        lines.extend(f"      {step.method.upper()} {step.path}" for step in journey.steps)
    lines.append("Stages:")
    lines.extend(f"  {stage.duration} -> {stage.target} VUs" for stage in spec.stages)
    lines.append("Thresholds:")
    for metric, exprs in spec.thresholds.items():
        lines.append(f"  {metric}: {', '.join(exprs)}")
    return "\n".join(lines)
